# Calculate the **Principal Component Analysis** 
# from Scratch in **Python**

In [2]:
import pandas as pd

df = pd.read_csv(
    filepath_or_buffer='https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', 
    header=None, 
    sep=',')

df.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class']
df.dropna(how="all", inplace=True) # drops the empty line at file-end

df.tail()

sepal_len  sepal_wid  petal_len  petal_wid           class
145        6.7        3.0        5.2        2.3  Iris-virginica
146        6.3        2.5        5.0        1.9  Iris-virginica
147        6.5        3.0        5.2        2.0  Iris-virginica
148        6.2        3.4        5.4        2.3  Iris-virginica
149        5.9        3.0        5.1        1.8  Iris-virginica

In [10]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [11]:
from sklearn.preprocessing import StandardScaler
X_std = StandardScaler().fit_transform(X)

In [49]:
cor_mat1 = np.corrcoef(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat1)
eig_pairs = [(eig_vals[i], eig_vecs[:,i]) for i in range(len(eig_vals))]
list(eig_pairs)

[(2.910818083752052,
  array([ 0.52237162, -0.26335492,  0.58125401,  0.56561105])),
 (0.9212209307072257,
  array([-0.37231836, -0.92555649, -0.02109478, -0.06541577])),
 (0.14735327830509534,
  array([-0.72101681,  0.24203288,  0.14089226,  0.6338014 ])),
 (0.020607707235625248,
  array([ 0.26199559, -0.12413481, -0.80115427,  0.52354627]))]

In [50]:
matrix_w = np.hstack((eig_pairs[1][1].reshape(4,1),
           eig_pairs[0][1].reshape(4,1)))

Y = X_std.dot(matrix_w)